### ISSUE TITLE
Benchmark the pretrained-rl-agent method

### ISSUE THREAD

**Issue by liuyuezhang** [mila-iqia/atari-representation-learning#55]
I tried to reproduce the result in Table 10, with
```bash
python -m scripts.run_probe --method pretrained-rl-agent
```
but got
```bash
-------Collecting samples----------
Deleting room_number for being too low in entropy! Sorry, dood!
Deleting enemy_skull_y for being too low in entropy! Sorry, dood!
Deleting key_monster_x for being too low in entropy! Sorry, dood!
Deleting key_monster_y for being too low in entropy! Sorry, dood!
Deleting level for being too low in entropy! Sorry, dood!
Deleting score_0 for being too low in entropy! Sorry, dood!
Deleting score_1 for being too low in entropy! Sorry, dood!
Deleting score_2 for being too low in entropy! Sorry, dood!
Duplicates: 98, Test Len: 8011
got episodes!
Total Steps: 27411
Traceback (most recent call last):
  File "/home/liuyuezhangadam/anaconda3/envs/pytorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liuyuezhangadam/anaconda3/envs/pytorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liuyuezhangadam/Git/atari-representation-learning/scripts/run_probe.py", line 87, in <module>
    run_probe(args)
  File "/home/liuyuezhangadam/Git/atari-representation-learning/scripts/run_probe.py", line 71, in run_probe
    trainer.train(tr_eps, val_eps, tr_labels, val_labels)
  File "/home/liuyuezhangadam/Git/atari-representation-learning/atariari/benchmark/probe.py", line 197, in train
    epoch_loss, accuracy = self.do_one_epoch(tr_eps, tr_labels)
  File "/home/liuyuezhangadam/Git/atari-representation-learning/atariari/benchmark/probe.py", line 143, in do_one_epoch
    preds = self.probe(x, k)
  File "/home/liuyuezhangadam/Git/atari-representation-learning/atariari/benchmark/probe.py", line 117,
wandb: Waiting for W&B process to finish, PID 30113
 in probe
    assert len(f.squeeze().shape) == 2, "if input is a batch of vectors you must specify an encoder!"
AssertionError: if input is a batch of vectors you must specify an encoder!
```

seems the encoder is simply defined as ```None``` in the code,

https://github.com/mila-iqia/atari-representation-learning/blob/017f9260fb53c45d34c80c5080a2b46148e4cfd6/scripts/run_probe.py#L36-L37

any help for fixing it to reproduce the result in Table 10? Or did I make any mistake?
Thanks, @ankeshanand

**Comment by eracah** [comment]
Hi Yuezhang,
Thanks for pointing this out. Looks like this functionality got lost in the refactoring process. I have fixed it in https://github.com/mila-iqia/atari-representation-learning/pull/56 

@ankeshanand, please merge

**Comment by ankeshanand** [comment]
I've merge it, thanks! 

@liuyuezhang You should also add `--probe-collect-mode pretrained_ppo` to the run command since results in Table 10 were reported with data collected from a PPO agent.

**Comment by liuyuezhang** [comment]
@eracah @ankeshanand Thanks for your efficient work and clarification!
